### ISSUE TITLE
Help with image size

### ISSUE THREAD

**Issue by sheri-thomson** [sheri-thomson/responsive-section#1]
@thomasjbradley

Markbot is accepting my 320 size but I noticed that the image sizes are bigger than what you're looking for. How do I make them smaller?

Also, when targeting my heading, it's including the images as part of it, essentially throwing off the margin left i"m trying to use.

**Comment by thomasjbradley** [comment]
*Re: images—*

The images should be set to a width of 100%, but they are inside `<div>` tags that have `padding` on the left & right at specific screen sizes.

---

*Re: heading—*

I don't fully understand what you mean about the heading. Can you give me an example, or maybe upload a screenshot?

**Comment by sheri-thomson** [comment]
<img width="1680" alt="screen shot 2017-12-17 at 10 21 44 pm" src="https://user-images.githubusercontent.com/31968878/34088671-c846e23c-e378-11e7-9f6c-6c47ccd0b576.png">

**Comment by sheri-thomson** [comment]
I was trying to get padding around the ```.section-body``` but had to target the ```<p>``` tag and ```<h2>``` separately

**Comment by sheri-thomson** [comment]
I figured it out :)
